-- FS PBX number translation configuration for FreeSWITCH mod_translate.
-- The XML handler reads this file on a translate.conf configuration request.


local DEBUG_MODE = false
local CACHE_KEY = "configuration:translate.conf"
local DEFAULT_CACHE_TTL = 3600

local cache = require "resources.functions.cache"

local function log(level, message)
    freeswitch.consoleLog(level, "[translate.conf.lua] " .. tostring(message) .. "\n")
end

local function debug_log(message)
    if DEBUG_MODE then
        log("NOTICE", message)
    end
end

local function build_configuration(dbh)
    local escape = require("resources.functions.xml").escape
    local xml = {
        [[<?xml version="1.0" encoding="UTF-8" standalone="no"?>]],
        [[<document type="freeswitch/xml">]],
        [[	<section name="configuration">]],
        [[		<configuration name="translate.conf" description="Number Translation Rules" autogenerated="true">]],
        [[			<profiles>]],
    }
    local current_profile

    -- One snapshot covers profiles and rules. LEFT JOIN retains empty profiles;
    -- UUID grouping also keeps legacy profiles with duplicate names separate.
    -- Order is legacy text: accept padded/unpadded numbers and put blanks last.
    local sql = [[
        SELECT p.number_translation_uuid, p.number_translation_name,
               p.number_translation_description,
               r.number_translation_detail_regex, r.number_translation_detail_replace
        FROM v_number_translations AS p
        LEFT JOIN v_number_translation_details AS r
            ON r.number_translation_uuid = p.number_translation_uuid
        WHERE p.number_translation_enabled = 'true'
        ORDER BY p.number_translation_name ASC, p.number_translation_uuid ASC,
                 CASE WHEN r.number_translation_detail_order ~ '^[0-9]+$'
                     THEN r.number_translation_detail_order::numeric END ASC NULLS LAST,
                 r.number_translation_detail_uuid ASC
    ]]

    local ok, err = dbh:query(sql, function(row)
        if row.number_translation_uuid ~= current_profile then
            if current_profile then
                xml[#xml + 1] = [[				</profile>]]
            end
            current_profile = row.number_translation_uuid
            xml[#xml + 1] = [[				<profile name="]] .. escape(row.number_translation_name)
                .. [[" description="]] .. escape(row.number_translation_description) .. [[">]]
        end

        local regex = row.number_translation_detail_regex
        if regex and regex ~= "" then
            -- Escape XML only: captures, backslashes and ${variables} are literal.
            xml[#xml + 1] = [[					<rule regex="]] .. escape(regex)
                .. [[" replace="]] .. escape(row.number_translation_detail_replace) .. [[" />]]
        end
    end)
    if not ok then
        error("Unable to read number translation rules: " .. tostring(err or "query failed"), 0)
    end

    if current_profile then
        xml[#xml + 1] = [[				</profile>]]
    end
    xml[#xml + 1] = [[			</profiles>]]
    xml[#xml + 1] = [[		</configuration>]]
    xml[#xml + 1] = [[	</section>]]
    xml[#xml + 1] = [[</document>]]
    return table.concat(xml, "\n")
end

local function generate_configuration()
    local dbh
    local ok, result = pcall(function()
        local Database = require "resources.functions.database"
        dbh = Database.new("system")
        if not dbh or not dbh:connected() then
            error("Unable to connect to the number translation database", 0)
        end
        return build_configuration(dbh)
    end)

    -- Release on both query errors and Lua exceptions, before publishing XML.
    if dbh then
        local released, err = pcall(dbh.release, dbh)
        if not released then
            log("ERR", "Unable to release the database connection: " .. tostring(err))
        end
    end
    if not ok then
        return nil, result
    end
    return result
end

local function main()
    local read_ok, cached_xml, cache_error = pcall(cache.get, CACHE_KEY)
    if read_ok and type(cached_xml) == "string" and cached_xml ~= "" then
        debug_log("Serving number translations from cache")
        return cached_xml
    end
    debug_log("Reading number translations from the database; cache unavailable: "
        .. tostring(read_ok and (cache_error or "empty") or cached_xml))

    local xml, err = generate_configuration()
    if not xml then
        -- A failed read must never replace the cache with empty or partial rules.
        log("ERR", "Unable to generate number translation configuration: " .. tostring(err))
        return nil
    end

    local ttl = (expire and expire.translate) or DEFAULT_CACHE_TTL
    local write_ok, stored, write_error = pcall(cache.set, CACHE_KEY, xml, ttl)
    if not write_ok or not stored then
        log("WARNING", "Serving generated number translations without caching: "
            .. tostring(write_ok and (write_error or "cache write failed") or stored))
    else
        debug_log("Generated and cached number translation configuration")
    end
    return xml
end

-- XML_STRING is the FreeSWITCH XML-handler contract; other state stays local.
XML_STRING = main()
