local diversion = require "resources.functions.diversion"

-- The dialplan owns bridging and fallback order. Transfer/internal routes only
-- remove a header previously generated by us, retaining forwarding metadata.
if argv[1] == "clear" then
    diversion.reset(session)
else
    diversion.apply(session)
end
