[program:fs-esl-listener-call-webhooks]
command=php /var/www/fspbx/artisan esl:listen-call-webhooks
directory=/var/www/fspbx
autostart=false
autorestart=true
startsecs=5
user=www-data
stderr_logfile=/var/log/fs-esl-listener-call-webhooks.err.log
stdout_logfile=/var/log/fs-esl-listener-call-webhooks.out.log
