-- Runs the real XML handler with isolated database/cache fixtures.
package.path = './resources/freeswitch_scripts/?.lua;' .. package.path
local handler = './resources/freeswitch_scripts/app/xml_handler/resources/scripts/configuration/translate.conf.lua'
local cache_key = 'configuration:translate.conf'

local function row(uuid, name, regex, replacement, description)
    return {
        number_translation_uuid = uuid,
        number_translation_name = name,
        number_translation_description = description,
        number_translation_detail_regex = regex,
        number_translation_detail_replace = replacement,
    }
end

local rows = {
    row('a', 'A & "quoted" profile', [[^(?<digits>44|49)(\d+)$]], [[${country}$1&"<>']], 'A & "quoted" description'),
    row('a', 'A & "quoted" profile', [[^(.*)$]], nil),
    row('a', 'A & "quoted" profile', ''),
    row('b', 'A & "quoted" profile', '^second$', '$1'), -- Duplicate legacy names stay separate.
    row('c', 'empty'), -- LEFT JOIN row for a profile with no rules.
}

local function run(options)
    options = options or {}
    local state = { reads = 0, writes = 0, queries = 0, opens = 0, releases = 0, loads = 0, logs = {} }
    local cached_xml = options.cached_xml
    freeswitch = { consoleLog = function(level, message)
        state.logs[#state.logs + 1] = { level, message }
    end }
    expire = options.expire
    XML_STRING = 'previous request'

    package.loaded['resources.functions.cache'] = {
        get = function(key)
            assert(key == cache_key)
            state.reads = state.reads + 1
            if options.read_exception then error('cache read failed') end
            return cached_xml, 'NOT FOUND'
        end,
        set = function(key, value, ttl)
            assert(key == cache_key)
            assert(state.releases == 1, 'Release the database before writing the cache.')
            state.writes = state.writes + 1
            state.ttl = ttl
            if options.write_exception then error('cache write failed') end
            if options.write_failure then return nil, 'cache write failed' end
            cached_xml = value
            return true
        end,
    }
    package.loaded['resources.functions.database'] = nil
    package.preload['resources.functions.database'] = function()
        state.loads = state.loads + 1
        return { new = function(name)
            assert(name == 'system')
            state.opens = state.opens + 1
            if options.open_exception then error('database connection failed') end
            if options.missing_handle then return nil end
            return {
                connected = function() return not options.disconnected end,
                release = function()
                    state.releases = state.releases + 1
                    if options.release_exception then error('release failed') end
                end,
                query = function(_, sql, callback)
                    state.queries = state.queries + 1
                    assert(type(sql) == 'string' and type(callback) == 'function')
                    for _, record in ipairs(options.rows or rows) do
                        callback(record)
                        if options.query_exception then error('query interrupted after a row') end
                    end
                    if options.query_failure then return false, 'query failed' end
                    return true
                end,
            }
        end }
    end

    local globals = {}
    for key, value in pairs(_G) do globals[key] = value end
    for _ = 1, options.requests or 1 do dofile(handler) end
    for key, value in pairs(_G) do
        assert(key == 'XML_STRING' or value == globals[key], 'Unexpected global state: ' .. key)
    end
    assert(expire == options.expire, 'Do not overwrite shared expiration settings.')
    if expire then assert(expire.translate == options.ttl) end
    state.xml = XML_STRING
    return state
end

local expected = table.concat({
    [[<?xml version="1.0" encoding="UTF-8" standalone="no"?>]],
    [[<document type="freeswitch/xml">]],
    [[	<section name="configuration">]],
    [[		<configuration name="translate.conf" description="Number Translation Rules" autogenerated="true">]],
    [[			<profiles>]],
    [[				<profile name="A &amp; &quot;quoted&quot; profile" description="A &amp; &quot;quoted&quot; description">]],
    [[					<rule regex="^(?&lt;digits&gt;44|49)(\d+)$" replace="${country}$1&amp;&quot;&lt;&gt;&apos;" />]],
    [[					<rule regex="^(.*)$" replace="" />]],
    [[				</profile>]],
    [[				<profile name="A &amp; &quot;quoted&quot; profile" description="">]],
    [[					<rule regex="^second$" replace="$1" />]],
    [[				</profile>]],
    [[				<profile name="empty" description="">]],
    [[				</profile>]],
    [[			</profiles>]],
    [[		</configuration>]],
    [[	</section>]],
    [[</document>]],
}, '\n')

local generated = run({ requests = 2 })
assert(generated.xml == expected, 'Preserve complete XML, profile boundaries, order and literal expressions.')
assert(generated.queries == 1 and generated.opens == 1 and generated.releases == 1)
assert(generated.reads == 2 and generated.writes == 1 and generated.ttl == 3600)
assert(#generated.logs == 0, 'Successful requests should stay quiet unless debugging is enabled.')

local hit = run({ cached_xml = expected })
assert(hit.xml == expected and hit.loads == 0 and hit.queries == 0 and hit.writes == 0)
assert(run({ cached_xml = '' }).xml == expected, 'Empty cache entries must be regenerated.')
assert(run({ read_exception = true }).xml == expected, 'Cache outages must fall back to the database.')
assert(run({ expire = { translate = '90' }, ttl = '90' }).ttl == '90')
assert(run({ expire = {} }).ttl == 3600)

local empty = run({ rows = {} })
assert(not empty.xml:find('<profile ', 1, true))
assert(empty.xml:find('</profiles>', 1, true) and empty.writes == 1 and empty.releases == 1)

for _, option in ipairs({ 'query_failure', 'query_exception', 'disconnected', 'open_exception', 'missing_handle' }) do
    local failed = run({ [option] = true })
    assert(failed.xml == nil and failed.writes == 0, option .. ' must not publish/cache partial or stale XML.')
    local acquired_handle = option ~= 'open_exception' and option ~= 'missing_handle'
    assert(failed.releases == (acquired_handle and 1 or 0), option .. ' must release acquired handles.')
    assert(#failed.logs == 1 and failed.logs[1][1] == 'ERR', option .. ' must explain the failure.')
end

for _, option in ipairs({ 'write_failure', 'write_exception', 'release_exception' }) do
    local failed = run({ [option] = true })
    assert(failed.xml == expected and failed.queries == 1 and failed.releases == 1)
    assert(#failed.logs == 1, option .. ' must log the error and still serve complete XML.')
end

print('PASS: exact XML, empty/duplicate profiles, literal expressions, one query, cache reuse/TTL, global isolation, and failure cleanup')
