import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

/**
* 1. IMPORT THE API SIDEBAR
* This file is created by the openapi-docs plugin inside your output directory.
* The path must be relative to this sidebars.js file.
*/
const apiReferenceSidebar = require("./docs/api/v1/sidebar.js");

const sidebars: SidebarsConfig = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    tutorialSidebar: [{ type: 'autogenerated', dirName: 'tutorials' }],

    apiSidebar: [
        {
            type: "category",
            label: "API Reference",
            collapsed: false,
            /**
             * 2. USE THE IMPORTED, PRE-SORTED ARRAY
             */
            items: apiReferenceSidebar,
        },
    ],

    // But you can create a sidebar manually
    /*
    tutorialSidebar: [
      'intro',
      'hello',
      {
        type: 'category',
        label: 'Tutorial',
        items: ['tutorial-basics/create-a-document'],
      },
    ],
     */
};

export default sidebars;
